name = "PlutoPages"
uuid = "d5dc3dd1-4774-47c7-8860-0a1ad9e34b8c"
authors = ["Luca Ferranti", "Fons van der Plas"]
version = "1.0.3"

[deps]
BetterFileWatching = "c9fd44ac-77b5-486c-9482-9798bd063cc6"
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Malt = "36869731-bdee-424d-aa32-cab38c994e3b"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MarkdownLiteral = "736d6165-7244-6769-4267-6b50796e6954"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoHooks = "0ff47ea0-7a50-410d-8455-4348d5de0774"
PlutoLinks = "0ff47ea0-7a50-410d-8455-4348d5de0420"
PlutoSliderServer = "2fc8631c-6f24-4c5b-bca7-cbb509c42db4"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
BetterFileWatching = "0.1"
CommonMark = "0.8, 0.9, 0.10, 1.0"
Gumbo = "0.8"
HypertextLiteral = "0.9, 1.0"
InteractiveUtils = "1"
JSON = "1"
LiveServer = "1.2"
Logging = "1"
Malt = "1"
Markdown = "1"
MarkdownLiteral = "0.1"
Pkg = "1"
Pluto = "0.20"
PlutoHooks = "0.0.5, 0.1"
PlutoLinks = "0.1.6"
PlutoSliderServer = "1"
PlutoUI = "0.7.55"
ProgressLogging = "0.1"
RelocatableFolders = "1"
SHA = "0.7,1"
ThreadsX = "0.1"
Unicode = "1"
YAML = "0.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
